# -*- org-html-validation-link: nil; -*-

#+SETUPFILE: theme.org
#+EXPORT_FILE_NAME: index.html
#+TITLE: Guitar Improvisation
#+SUBTITLE: Playing over the i-iv-V chord progression

This document describes a framework for guitar improvisation, using
the ~i-iv-V~ chord progression (derived from the minor scale) as an
example. All examples are in the key of ~A~, so the chords are ~Amin~ →
~Dmin~ → ~Emaj~.

* Open chords
An open chord is a chord that is played with one or more open
strings. Here's the most common ways of playing ~Amin~, ~Dmin~ and ~Emaj~:

#+attr_guitar: :container row
#+begin_src lisp
(guitar:diagram (:title "A minor (open)" :frets 4)
  (6 x)
  (5 0 "R" (:stroked :highlight))
  (4 2 "5")
  (3 2 "R" (:filled :highlight))
  (2 1 "b3")
  (1 0 "5" (:stroked :highlight)))

(guitar:diagram (:title "D minor (open)" :frets 4)
  (6 x)
  (5 x)
  (4 0 "R" (:stroked :highlight))
  (3 2 "5")
  (2 3 "R" (:filled :highlight))
  (1 1 "b3"))

(guitar:diagram (:title "E major (open)" :frets 4)
  (6 0 "R" (:stroked :highlight))
  (5 2 "5")
  (4 2 "R" (:filled :highlight))
  (3 1 "3")
  (2 0 "5" :stroked)
  (1 0 "R" (:stroked :highlight)))
#+end_src

Note that the bottom strings are not always played. This is because
we want to play the _root note_ at the bottom of the chord (this is not
100% required, but it's the most basic version of the chord).

* Arpeggios
An _arpeggio_ is a chord played sequentially in an ascending/descending
order. These are very useful when improvising, because they contain
notes that are consonant with the chord they're played over.

#+attr_guitar: :container row
#+begin_src lisp
(guitar:diagram (:title "A minor arpeggio" :frets 6 :start 4 :indicator 5)
        (6 5 "R" (:filled :highlight))
        (6 8 "b3")
        (5 7 "5")
        (4 7 "R" (:filled :highlight))
        (3 5 "b3")
        (2 5 "5")
        (1 5 "R" (:filled :highlight)))

(guitar:diagram (:title "D minor arpeggio" :frets 6 :start 4 :indicator 5)
  (6 5 "5")
  (5 5 "R" (:filled :highlight))
  (5 8 "b3")
  (4 7 "5")
  (3 7 "R" (:filled :highlight))
  (2 6 "b3")
  (1 5 "5"))

(guitar:diagram (:title "E major arpeggio" :frets 6 :start 4 :indicator 5)
  (6 4 "3")
  (6 7 "5")
  (5 7 "R" (:filled :highlight))
  (4 6 "3")
  (3 4 "5")
  (2 5 "R" (:filled :highlight))
  (1 4 "3")
  (1 7 "5"))
#+end_src

The red dots correspond to the _root note_ of the chord (e.g. ~D~ for the
~Dmin~ chord).

Try playing these one after another at a set tempo (with a
metronome). After you can play them ascending/descending, try mixing
it up and come up with some melodies over the ~i-iv-V~ progression.

** TODO Fix images                                                   :noexport:

* Pentatonic scale
Playing arpeggios over chords sound good, but it's not very
interesting. Let's add some notes from the _pentatonic scale_. To start,
we'll only explore the pentatonic scale built on top of the ~Amin~
chord.

#+attr_guitar: :container small
#+begin_src lisp
(guitar:diagram (:title "A minor pentatonic" :frets 6 :start 4 :indicator 5)
  (6 5 "R" (:filled :highlight))
  (6 8 "b3")
  (5 5 "4")
  (5 7 "5")
  (4 5 "b7")
  (4 7 "R" (:filled :highlight))
  (3 5 "b3")
  (3 7 "4")
  (2 5 "5")
  (2 8 "b7")
  (1 5 "R" (:filled :highlight))
  (1 8 "b3"))
#+end_src

When improvising, focus on the notes from the arpeggio of the current
chord and sprinkle some notes from the ~Amin~ pentatonic scale when you want
to spice things up.

* Natural minor scale
Let's add another layer of notes to the pentatonic scale.

#+attr_guitar: :container small
#+begin_src lisp
(guitar:diagram (:title "A natural minor" :frets 6 :start 4 :indicator 5)
  (6 5 "R" (:filled :highlight))
  (6 7 "2" (:stroked :new))
  (6 8 "b3")
  (5 5 "4")
  (5 7 "5")
  (5 8 "b6" (:stroked :new))
  (4 5 "b7")
  (4 7 "R" (:filled :highlight))
  (3 4 "2" (:stroked :new))
  (3 5 "b3")
  (3 7 "4")
  (2 5 "5")
  (2 6 "b6" (:stroked :new))
  (2 8 "b7")
  (1 5 "R" (:filled :highlight))
  (1 7 "2" (:stroked :new))
  (1 8 "b3"))
#+end_src

The blue notes are the additional notes added. These notes form the
_natural minor scale_. When playing notes outside the arpeggio and
pentatonic scale, try not to linger on them too long. A good way is to
using them as _passing notes_, for example between two chord tones (from
the arpeggio).

* Triads
A triad is a chord consisting of three notes - the root, the third and
the fifth. There are many places to play triads on the guitar neck -
we're going to focus on a set of triads that lies on strings 2, 3
and 4. These are shown on top of the A natural minor scale for
reference.

#+attr_guitar: :container row
#+begin_src lisp
(guitar:diagram (:title "A minor triad" :frets 6 :start 4 :indicator 5)
  (6 5 "" (:stroked :ref))
  (6 7 "" (:stroked :ref))
  (6 8 "" (:stroked :ref))
  (5 5 "" (:stroked :ref))
  (5 7 "" (:stroked :ref))
  (5 8 "" (:stroked :ref))
  (4 5 "" (:stroked :ref))
  (4 7 "R" (:filled :highlight))
  (3 4 "" (:stroked :ref))
  (3 5 "b3")
  (3 7 "" (:stroked :ref))
  (2 5 "5")
  (2 6 "" (:stroked :ref))
  (2 8 "" (:stroked :ref))
  (1 5 "" (:stroked :ref))
  (1 7 "" (:stroked :ref))
  (1 8 "" (:stroked :ref)))

(guitar:diagram (:title "D minor triad" :frets 6 :start 4 :indicator 5)
  (6 5 "" (:stroked :ref))
  (6 7 "" (:stroked :ref))
  (6 8 "" (:stroked :ref))
  (5 5 "" (:stroked :ref))
  (5 7 "" (:stroked :ref))
  (5 8 "" (:stroked :ref))
  (4 5 "" (:stroked :ref))
  (4 7 "5")
  (3 4 "" (:stroked :ref))
  (3 5 "" (:stroked :ref))
  (3 7 "R" (:filled :highlight))
  (2 5 "" (:stroked :ref))
  (2 6 "b3")
  (2 8 "" (:stroked :ref))
  (1 5 "" (:stroked :ref))
  (1 7 "" (:stroked :ref))
  (1 8 "" (:stroked :ref)))

(guitar:diagram (:title "E major triad" :frets 6 :start 4 :indicator 5)
  (6 5 "" (:stroked :ref))
  (6 7 "" (:stroked :ref))
  (6 8 "" (:stroked :ref))
  (5 5 "" (:stroked :ref))
  (5 7 "" (:stroked :ref))
  (5 8 "" (:stroked :ref))
  (4 6 "3")
  (4 7 "" (:stroked :ref))
  (3 4 "5")
  (3 5 "" (:stroked :ref))
  (3 7 "" (:stroked :ref))
  (2 5 "R" (:filled :highlight))
  (2 6 "" (:stroked :ref))
  (2 8 "" (:stroked :ref))
  (1 5 "" (:stroked :ref))
  (1 7 "" (:stroked :ref))
  (1 8 "" (:stroked :ref)))
#+end_src

These three are nice, because with them you can play the whole ~i-iv-V~ chord
progression with minimal note movement. This means that they naturally
_voice lead_ into each other.

When you want to add some harmony behind your playing, you can
interleave these triads between your melody notes. This works
especially good if the _top note_ of the triad is part of the melody.

Note that the ~Emaj~ triad contains a note that does not exist in the
natural minor scale. This note lies _just below the root note_ of the ~i~
chord (the _tonic_). This note, also called the _leading tone_, is special
since it has a strong "pull" towards the tonic. The main purpose of
the ~V~ chord (~Emaj~ in this case) is to resolve back "home".
